# Generated by Django 5.0.1 on 2024-02-08 21:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cohort',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('NAME', models.CharField(max_length=100)),
                ('DESCRIPTION', models.TextField()),
                ('YEAR', models.IntegerField()),
                ('START_DATE', models.DateField()),
                ('END_DATE', models.DateField()),
                ('IS_ACTIVE', models.BooleanField(default=True)),
                ('DATE_CREATED', models.DateTimeField(auto_now_add=True)),
                ('DATE_MODIFIED', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='IMUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('FIRST_NAME', models.CharField(max_length=30)),
                ('LAST_NAME', models.CharField(max_length=30)),
                ('IS_ACTIVE', models.BooleanField(default=True)),
                ('USER_TYPE', models.CharField(choices=[('EIT', 'Engineering Intern'), ('TF', 'Teaching Fellow'), ('ADS', 'Admin Staff'), ('ADM', 'Admin')], max_length=3)),
                ('DATE_CREATED', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='CohortMember',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('IS_ACTIVE', models.BooleanField(default=True)),
                ('DATE_CREATED', models.DateTimeField(auto_now_add=True)),
                ('DATE_MODIFIED', models.DateTimeField(auto_now=True)),
                ('COHORT', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.cohort')),
                ('AUTHOR', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='authored_cohort_members', to='users.imuser')),
                ('MEMBER', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cohort_members', to='users.imuser')),
            ],
        ),
        migrations.AddField(
            model_name='cohort',
            name='AUTHOR',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.imuser'),
        ),
    ]
