# Generated by Django 5.0.1 on 2024-02-14 16:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_alter_imuser_user_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='imuser',
            name='USER_TYPE',
            field=models.CharField(choices=[('choice', 'SELECT USER'), ('EIT', 'EIT'), ('Teaching Fellow', 'TEACHING FELLOW'), ('Admin Staff', 'ADMIN STAFF'), ('Admin', 'ADMIN')], max_length=50),
        ),
    ]
