# Generated by Django 5.0.1 on 2024-02-22 03:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("main", "0002_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="query",
            name="resolution_status",
            field=models.CharField(
                choices=[
                    ("PENDING", "Pending"),
                    ("IN_PROGRESS", "In Progress"),
                    ("DECLINED", "Declined"),
                    ("RESOLVED", "Resolved"),
                ],
                default="PENDING",
                max_length=50,
            ),
        ),
        migrations.DeleteModel(name="ResolutionStatus",),
    ]
