# Generated by Django 5.0.1 on 2024-02-22 11:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("main", "0004_classschedule_course_classschedule_facilitator_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="classschedule",
            name="date_created",
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name="classschedule",
            name="date_modified",
            field=models.DateTimeField(auto_now=True, null=True),
        ),
    ]
