# Generated by Django 5.0.1 on 2024-02-13 11:07

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("main", "0001_initial"),
        ("users", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="classattendance",
            name="attendee",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="attendee_members",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="classattendance",
            name="author",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="authored_attendance",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="classschedule",
            name="cohort",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="users.cohort"
            ),
        ),
        migrations.AddField(
            model_name="classattendance",
            name="class_schedule",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="main.classschedule"
            ),
        ),
        migrations.AddField(
            model_name="query",
            name="assigned_to",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="assigned",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="query",
            name="author",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="author",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="query",
            name="submitted_by",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL
            ),
        ),
        migrations.AddField(
            model_name="querycomment",
            name="author",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL
            ),
        ),
        migrations.AddField(
            model_name="querycomment",
            name="query",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="main.query"
            ),
        ),
        migrations.AddField(
            model_name="query",
            name="resolution_status",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="main.resolutionstatus"
            ),
        ),
    ]
