# Generated by Django 5.0.1 on 2024-02-10 12:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_classschedule_classattendance_query_querycomment'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='classschedule',
            name='cohort',
        ),
        migrations.RemoveField(
            model_name='classschedule',
            name='organizer',
        ),
        migrations.RemoveField(
            model_name='query',
            name='assigned_to',
        ),
        migrations.RemoveField(
            model_name='query',
            name='author',
        ),
        migrations.RemoveField(
            model_name='query',
            name='submitted_by',
        ),
        migrations.RemoveField(
            model_name='querycomment',
            name='query',
        ),
        migrations.RemoveField(
            model_name='querycomment',
            name='author',
        ),
        migrations.DeleteModel(
            name='ClassAttendance',
        ),
        migrations.DeleteModel(
            name='ClassSchedule',
        ),
        migrations.DeleteModel(
            name='Query',
        ),
        migrations.DeleteModel(
            name='QueryComment',
        ),
    ]
