# Generated by Django 5.0.1 on 2024-02-10 13:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_remove_classschedule_cohort_and_more'),
        ('users', '0004_alter_imuser_user_type'),
    ]

    operations = [
        migrations.CreateModel(
            name='ClassSchedule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('start_date_and_time', models.DateTimeField()),
                ('end_date_and_time', models.DateTimeField()),
                ('is_repeated', models.BooleanField(default=False)),
                ('repeat_frequency', models.IntegerField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('venue', models.CharField(max_length=255)),
                ('cohort', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='class_schedules', to='users.cohort')),
                ('organizer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='organized_classes', to='users.imuser')),
            ],
        ),
    ]
